research_task:
  description: >
    在 {customer_domain} 的背景下，对客户和竞争对手进行全面研究。
    确保您找到任何有趣且相关的信息，因为当前年份是 2024 年。
    我们正在与他们合作开展以下项目：{project_description}。
  expected_output: >
    一份关于客户及其客户和竞争对手的完整中文版报告，包括他们的人口统计、偏好、市场定位和受众参与度。

project_understanding_task:
  description: >
    了解 {project_description} 的项目细节和目标受众。
    审查提供的任何材料并根据需要收集其他信息。
  expected_output: >
    项目的详细中文版摘要和目标受众的中文版概况。

marketing_strategy_task:
  description: >
    为客户 {customer_domain} 的项目 {project_description} 制定全面的营销策略。
    利用研究任务和项目理解任务中的见解来创建高质量的策略。
  expected_output: >
    一份详细的营销策略中文版文档，概述目标、目标受众、关键信息和建议的策略，确保包含名称、策略、渠道和关键绩效指标。

campaign_idea_task:
  description: >
    为 {project_description} 开发创意营销活动方案。
    确保这些方案具有创新性、吸引力并且与整体营销策略保持一致。
  expected_output: >
    5 个活动方案的中文版列表，每个方案都包含简要描述和预期影响。

copy_creation_task:
  description: >
    根据 {project_description} 批准的活动方案创建营销文案。
    确保文案引人入胜、清晰明了，并针对目标受众量身定制。
  expected_output: >
    每个活动方案的中文版营销文案。